version: '3.8'

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES-USER=admin
      - POSTGRES-PASSWORD=admin
      - POSTGRES-DB=gestao_vagas